apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: IshitaCluster2
  region: ap-south-1
 
nodeGroups: 
  - name: ng4
    minSize: 2
    maxSize: 5
    instancesDistribution: 
        maxPrice: 0.017
        instanceTypes: ["t3.micro,t3.small"]
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 50
        spotInstancePools: 2
    ssh:
       publicKeyPath: ~/.ssh/Ishitaeks.pub

