kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-efs
provisioner: Ishita-1/NFS-1
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-wordpress
  
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-efs
  resources:
    requests:
      storage: 10Gi
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-mysql
  
spec:
  storageClassName: nfs-efs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
